// Runtime signatures of the DCS locations the production hooks use.
// GENERATED by tools/gen_hook_sigs.py from tools/hooks_manifest.json and the
// DCS binaries listed in kModules; do not edit. src/reloc.h reads it.
#pragma once

#include <cstdint>

namespace hooksig {

enum Kind : uint8_t { kVtable, kCode, kImport, kExport };
// How a kCode location is found again: unique pattern, slot of a vtable
// entry (pattern verified at the target), or `jmp [IAT]` by import name.
enum Via : uint8_t { kPattern, kViaVtable, kImportThunk };

struct Module {
  const wchar_t* name;
  uint32_t timestamp, sizeOfImage;  // the analysed build
};
struct Mask {  // bytes zeroed before hashing, relative to the location
  int32_t at;
  uint16_t len;
};
struct Loc {
  const char* id;
  uint8_t module;
  Kind kind;
  uint32_t rva;  // recorded
  const char* rtti;  // kVtable: RTTI type name, COL offset, prefix match, entry count (0 = unchecked)
  uint32_t colOffset;
  bool rttiPrefix;
  uint16_t vtableLen;
  Via via;  // kCode
  const char* pattern;  // location = match + patOffset
  int32_t patOffset;
  uint16_t vtable, slot;  // kViaVtable: Loc index and slot
  const char* dll;   // kImport, kImportThunk
  const char* name;  // kImport, kImportThunk, kExport
  int32_t fnAt;  // kCode gate: masked FNV of [location + fnAt, + fnLen)
  uint32_t fnLen;
  uint64_t fnHash;
  uint32_t maskFirst, maskCount;  // into kMasks
};
struct Hash {  // a CodeIs check: [location + at, + len)
  uint16_t loc;
  int32_t at;
  uint32_t len;
  uint64_t hash, masked;
};

enum Id : uint16_t {
  NG_StructBufferManager_vtbl,
  NG_StructBufferManager_allocate,
  NG_StructBufferManager_scan,
  NG_StructBufferManager_reset,
  NG_iat_ed_mutex_lock,
  NG_iat_ed_mutex_unlock,
  NG_SceneRenderable_render_triCounterAdd,
  NG_StructBufferManager_scan_pageBytesImm,
  ED_ED_get_time,
  ED_SyncTaskQueue_proceed_getTimeCall0,
  ED_SyncTaskQueue_proceed_getTimeCall1,
  ED_SyncTaskQueue_proceed_getTimeCall2,
  ED_SyncTaskQueue_proceed_getTimeCall3,
  DX_DX11Texture_vtbl,
  DX_DX11Texture_requestMip,
  DX_SConstantBuffer_vtbl,
  DX_SConstantBuffer_SetConstantBuffer,
  VIS_GraphSceneObject_vtbl,
  VIS_GraphSceneObject_collectRenderables,
  VIS_GraphSceneObject_partitionWeight,
  ANIM_CharacterInstanceGraphicsReflection_vtbl,
  ANIM_CharacterInstanceGraphicsReflection_collectRenderables,
  ANIM_CharacterInstanceGraphicsReflection_partitionWeight,
  NG_ShadowMapRenderable_vtbl,
  NG_ShadowMapRenderable_render,
  NG_ModelMaterialMT_vtbl,
  GC_CascadeShadowPass_vtbl,
  GC_CascadeShadowPass_execute,
  DX_DX11Renderer_vtbl,
  DX_DX11Renderer_draw,
  NG_ModelMaterialMT_drawShadow,
  NG_ModelMaterialMT_submit,
  NG_model_globals,
  NG_iat_PropertiesSet_getTexture,
  NG_iat_Texture2dProperties_valid,
  DX_DX11Shader_vtbl,
  DX_DX11Shader_setTexture,
  DX_DX11Shader_dtor,
  DX_DX11Texture_getDesc,
  DX_DX11Texture_compatible,
  DX_DX11Texture_getSRV,
  DX_DX11Texture_slot18,
  DX_DX11Texture_slot11,
  DX_DX11TextureFromFileInternalImpl_vtbl,
  DX_DX11TextureArrayFromFileInternalImpl_vtbl,
  DX_DX11TextureInternalDummy_vtbl,
  DX_DX11TextureFromFileInternalImpl_slot4,
  DX_DX11TextureInternalDummy_slot4,
  DX_ret0_stub,
  DX_STechnique_vtbl,
  DX_SPassBlock_vtbl,
  DX_CEffect_vtbl,
  DX_CEffect_GetDevice,
  DX_SShaderGlobalVariable_vtbl,
  DX_SShaderGlobalVariable_GetVertexShader,
  DX_DX11Shader_ctor_fieldStores,
  DX_DX11Shader_keyBuilder,
  DX_DX11Shader_macroBuilder,
  kCount
};

inline constexpr Module kModules[] = {
    {L"NGModel.dll", 0x6aae1e68u, 0x7b000u},
    {L"edCore.dll", 0x6aae1d76u, 0xaad000u},
    {L"dx11backend.dll", 0x6aae1d9du, 0x199000u},
    {L"Visualizer.dll", 0x6ac12454u, 0x312000u},
    {L"animator.dll", 0x6aae1e0fu, 0xda000u},
    {L"GraphicsCore.dll", 0x6aae1dbfu, 0x12a000u},
};

inline constexpr Mask kMasks[] = {
    {0, 14}, {43, 4}, {57, 4}, {109, 4}, {71, 4}, {87, 4}, {177, 4}, {244, 4},
    {259, 4}, {-8, 4}, {0, 1}, {-15, 4}, {1, 4}, {91, 4}, {158, 4}, {173, 4},
    {5, 4}, {29, 4}, {60, 4}, {1, 4}, {9, 4}, {62, 4}, {78, 4}, {86, 4},
    {94, 4}, {176, 4}, {-60, 4}, {-52, 4}, {1, 4}, {17, 4}, {25, 4}, {33, 4},
    {115, 4}, {-92, 4}, {-84, 4}, {-31, 4}, {-15, 4}, {-7, 4}, {1, 4}, {83, 4},
    {-174, 4}, {-166, 4}, {-113, 4}, {-97, 4}, {-89, 4}, {-81, 4}, {1, 4}, {74, 4},
    {96, 4}, {110, 4}, {49, 4}, {4, 4}, {4, 4}, {12, 4}, {28, 4}, {44, 4},
    {60, 4}, {79, 4}, {45, 4}, {57, 4}, {62, 4}, {78, 4}, {90, 4}, {95, 4},
    {125, 4}, {137, 4}, {142, 4}, {155, 4}, {48, 4}, {57, 4}, {104, 4}, {113, 4},
    {131, 4}, {140, 4}, {318, 4}, {96, 4}, {202, 4}, {235, 4}, {5, 4}, {82, 4},
    {93, 4}, {212, 4}, {16, 4}, {34, 4}, {8, 4}, {38, 4}, {65, 4}, {78, 4},
    {83, 4}, {89, 4}, {99, 4}, {104, 4}, {111, 4}, {116, 4}, {14, 4}, {23, 4},
    {31, 4}, {61, 4}, {143, 4}, {30, 4}, {43, 4}, {-259, 4}, {-222, 4}, {-202, 4},
    {-196, 4}, {-120, 4}, {-100, 4}, {-94, 4}, {-71, 4}, {16, 4}, {29, 4}, {264, 4},
    {284, 4}, {290, 4}, {366, 4}, {386, 4}, {392, 4}, {415, 4}, {487, 4}, {68, 4},
    {88, 4}, {94, 4}, {170, 4}, {197, 4}, {210, 4}, {223, 4}, {231, 4}, {260, 4},
    {274, 4}, {294, 4}, {302, 4}, {311, 4}, {326, 4}, {339, 4}, {347, 4}, {36, 4},
};

inline constexpr Loc kLocs[kCount] = {
    // NG.StructBufferManager.vtbl
    {"NG.StructBufferManager.vtbl", 0, kVtable, 0x58650u,
     ".?AVStructBufferManager@model@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 0u, 0u},
    // NG.StructBufferManager.allocate
    {"NG.StructBufferManager.allocate", 0, kCode, 0xbf30u,
     nullptr, 0u, false, 0,
     kPattern, "?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? 48 83 EC 20 49 8B F1 41 8B F8 8B EA 48 8B D9 4C 8D 71 20", 0, 0, 0,
     nullptr, nullptr,
     0, 136u, 0x5a6cfffb0b8aa8adull, 0u, 4u},
    // NG.StructBufferManager.scan
    {"NG.StructBufferManager.scan", 0, kCode, 0xc1b0u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 48 89 6C 24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57 48 83 EC 50 41 8B E8", 0, 0, 0,
     nullptr, nullptr,
     0, 347u, 0x76fd3320d0f758f6ull, 4u, 5u},
    // NG.StructBufferManager.reset
    {"NG.StructBufferManager.reset", 0, kCode, 0xbd80u,
     nullptr, 0u, false, 0,
     kPattern, "48 8B 41 08 48 8B 49 10 48 3B C1 74 16 45 33 C0", 0, 0, 0,
     nullptr, nullptr,
     0, 36u, 0xaca02bd92cab9bceull, 9u, 0u},
    // NG.iat.ed_mutex_lock
    {"NG.iat.ed_mutex_lock", 0, kImport, 0x57720u,
     nullptr, 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     "edcore.dll", "?lock@mutex@ed@@QEAAXXZ",
     0, 0u, 0x0000000000000000ull, 9u, 0u},
    // NG.iat.ed_mutex_unlock
    {"NG.iat.ed_mutex_unlock", 0, kImport, 0x57718u,
     nullptr, 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     "edcore.dll", "?unlock@mutex@ed@@QEAAXXZ",
     0, 0u, 0x0000000000000000ull, 9u, 0u},
    // NG.SceneRenderable.render.triCounterAdd
    {"NG.SceneRenderable.render.triCounterAdd", 0, kCode, 0x44371u,
     nullptr, 0u, false, 0,
     kPattern, "?? 48 01 82 E8 01 00 00 48 8B 51 10 4C 8D 43 64", 0, 0, 0,
     nullptr, nullptr,
     -33, 140u, 0xe4714409aa860f93ull, 9u, 2u},
    // NG.StructBufferManager.scan.pageBytesImm
    {"NG.StructBufferManager.scan.pageBytesImm", 0, kCode, 0xc206u,
     nullptr, 0u, false, 0,
     kPattern, "B8 ?? ?? ?? ?? F7 F7 3B E8 0F 42 E8 4D 2B C8 48 B8 AB AA AA AA AA AA AA 2A", 0, 0, 0,
     nullptr, nullptr,
     -86, 347u, 0x76fd3320d0f758f6ull, 11u, 5u},
    // ED.ED_get_time
    {"ED.ED_get_time", 1, kCode, 0xa3750u,
     nullptr, 0u, false, 0,
     kPattern, "48 83 EC 28 E8 ?? ?? ?? ?? 48 8B C8 0F 57 C0 48 85 C0", 0, 0, 0,
     nullptr, nullptr,
     0, 69u, 0x53491ce83ad4c66bull, 16u, 3u},
    // ED.SyncTaskQueue.proceed.getTimeCall0
    {"ED.SyncTaskQueue.proceed.getTimeCall0", 1, kCode, 0x37b6du,
     nullptr, 0u, false, 0,
     kPattern, "E8 ?? ?? ?? ?? 0F 28 F0 E9 ?? ?? ?? ?? 48 8B 07 90 48 3B C3", 0, 0, 0,
     nullptr, nullptr,
     -45, 255u, 0xed76d3d7ab04b02cull, 19u, 7u},
    // ED.SyncTaskQueue.proceed.getTimeCall1
    {"ED.SyncTaskQueue.proceed.getTimeCall1", 1, kCode, 0x37baau,
     nullptr, 0u, false, 0,
     kPattern, "E8 ?? ?? ?? ?? 0F 28 F0 48 85 FF 74 65 48 8B CF", 0, 0, 0,
     nullptr, nullptr,
     -106, 255u, 0xed76d3d7ab04b02cull, 26u, 7u},
    // ED.SyncTaskQueue.proceed.getTimeCall2
    {"ED.SyncTaskQueue.proceed.getTimeCall2", 1, kCode, 0x37bcau,
     nullptr, 0u, false, 0,
     kPattern, "E8 ?? ?? ?? ?? F2 0F 5C C6 66 0F 2F C7 77 4C 48 8B 3B", 0, 0, 0,
     nullptr, nullptr,
     -138, 255u, 0xed76d3d7ab04b02cull, 33u, 7u},
    // ED.SyncTaskQueue.proceed.getTimeCall3
    {"ED.SyncTaskQueue.proceed.getTimeCall3", 1, kCode, 0x37c1cu,
     nullptr, 0u, false, 0,
     kPattern, "E8 ?? ?? ?? ?? F2 0F 5C C6 48 8B 5C 24 58 48 8B 74 24 60", 0, 0, 0,
     nullptr, nullptr,
     -220, 255u, 0xed76d3d7ab04b02cull, 40u, 7u},
    // DX.DX11Texture.vtbl
    {"DX.DX11Texture.vtbl", 2, kVtable, 0xb7140u,
     ".?AVDX11Texture@RenderAPI@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 47u, 0u},
    // DX.DX11Texture.requestMip
    {"DX.DX11Texture.requestMip", 2, kCode, 0x49e90u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 7C 24 20 41 56 48 83 EC 30 48 8B 81 88 01 00 00", 0, 0, 0,
     nullptr, nullptr,
     0, 114u, 0x14f6694458fe9b98ull, 47u, 3u},
    // DX.SConstantBuffer.vtbl
    {"DX.SConstantBuffer.vtbl", 2, kVtable, 0xb9400u,
     ".?AUSConstantBuffer@D3DX11Effects@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 50u, 0u},
    // DX.SConstantBuffer.SetConstantBuffer
    {"DX.SConstantBuffer.SetConstantBuffer", 2, kCode, 0x67970u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 57 48 83 EC 20 F6 41 5C 02 48 8B FA", 0, 0, 0,
     nullptr, nullptr,
     0, 123u, 0x1c1601e728aabd00ull, 50u, 1u},
    // VIS.GraphSceneObject.vtbl
    {"VIS.GraphSceneObject.vtbl", 3, kVtable, 0x20d7e8u,
     ".?AVGraphSceneObject@Graphics@@", 72u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 51u, 0u},
    // VIS.GraphSceneObject.collectRenderables
    {"VIS.GraphSceneObject.collectRenderables", 3, kCode, 0x1a8723u,
     nullptr, 0u, false, 0,
     kImportThunk, nullptr, 0, 0, 0,
     "graphicsvista.dll", "?collectRenderables@GraphSceneObject@Graphics@@UEAAXIPEAPEBUCollectionInfo@render@@QEB_NPEAPEAV?$vector@PEAUISceneRenderable@render@@V?$allocator@PEAUISceneRenderable@render@@@ed@@@ed@@AEAUILightProbeSampler@4@@Z",
     0, 0u, 0x0000000000000000ull, 51u, 0u},
    // VIS.GraphSceneObject.partitionWeight
    {"VIS.GraphSceneObject.partitionWeight", 3, kCode, 0x63110u,
     nullptr, 0u, false, 0,
     kViaVtable, "F3 0F 10 41 30 C3 CC CC CC CC CC CC CC CC CC CC", 0, 17, 2,
     nullptr, nullptr,
     0, 6u, 0x0a10ee7fe2764a75ull, 51u, 0u},
    // ANIM.CharacterInstanceGraphicsReflection.vtbl
    {"ANIM.CharacterInstanceGraphicsReflection.vtbl", 4, kVtable, 0x93650u,
     ".?AVCharacterInstanceGraphicsReflection@Animator@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 51u, 0u},
    // ANIM.CharacterInstanceGraphicsReflection.collectRenderables
    {"ANIM.CharacterInstanceGraphicsReflection.collectRenderables", 4, kCode, 0x5c760u,
     nullptr, 0u, false, 0,
     kPattern, "85 D2 0F 84 ?? ?? ?? ?? 48 8B C4 89 50 10 48 89 48 08", 0, 0, 0,
     nullptr, nullptr,
     0, 34u, 0xbdcf5412e2927cabull, 51u, 1u},
    // ANIM.CharacterInstanceGraphicsReflection.partitionWeight
    {"ANIM.CharacterInstanceGraphicsReflection.partitionWeight", 4, kCode, 0x5cb40u,
     nullptr, 0u, false, 0,
     kViaVtable, "F3 0F 10 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC", 0, 20, 2,
     nullptr, nullptr,
     0, 9u, 0x83382aad990607d9ull, 52u, 1u},
    // NG.ShadowMapRenderable.vtbl
    {"NG.ShadowMapRenderable.vtbl", 0, kVtable, 0x59828u,
     ".?AVShadowMapRenderable@model@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 53u, 0u},
    // NG.ShadowMapRenderable.render
    {"NG.ShadowMapRenderable.render", 0, kCode, 0x443e0u,
     nullptr, 0u, false, 0,
     kPattern, "48 8B 51 10 48 8B 4A 10 4C 8B 82 C0 00 00 00 48 8B 01", 0, 0, 0,
     nullptr, nullptr,
     0, 22u, 0x662666bd7f55ca1cull, 53u, 0u},
    // NG.ModelMaterialMT.vtbl
    {"NG.ModelMaterialMT.vtbl", 0, kVtable, 0x592f0u,
     ".?AVModelMaterialMT@model@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 53u, 0u},
    // GC.CascadeShadowPass.vtbl
    {"GC.CascadeShadowPass.vtbl", 5, kVtable, 0xd9b68u,
     ".?AV?$TBaseRenderingPassWithData@UCascadeShadowPassData@?1??parseShadowMap@ShadowMapModule@render@@EEAAXHAEBVMatrixf@osg@@0@Z@V<lambda_1>@", 0u, true, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 53u, 0u},
    // GC.CascadeShadowPass.execute
    {"GC.CascadeShadowPass.execute", 5, kCode, 0xa6ec0u,
     nullptr, 0u, false, 0,
     kPattern, "4C 8B C2 48 8D 51 48 48 83 C1 60 E9 ?? ?? ?? ?? 4C 8B C2", 0, 0, 0,
     nullptr, nullptr,
     0, 83u, 0x74d07061ffe21c31ull, 53u, 5u},
    // DX.DX11Renderer.vtbl
    {"DX.DX11Renderer.vtbl", 2, kVtable, 0xb2a60u,
     ".?AVDX11Renderer@RenderAPI@@", 0u, false, 92,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 58u, 0u},
    // DX.DX11Renderer.draw
    {"DX.DX11Renderer.draw", 2, kCode, 0x14870u,
     nullptr, 0u, false, 0,
     kPattern, "40 53 56 57 41 57 48 83 EC 38 48 83 79 28 00 45 8B F9", 0, 0, 0,
     nullptr, nullptr,
     0, 159u, 0x126761832eeed8d1ull, 58u, 10u},
    // NG.ModelMaterialMT.drawShadow
    {"NG.ModelMaterialMT.drawShadow", 0, kCode, 0x17750u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 10 48 89 6C 24 18 56 57 41 56 48 83 EC 30 48 8B FA 48 8B F1 8B 92 D0 00 00 00 49 8B E8 8B 87 D4 00 00 00 89 81 8C 01 00 00 48 8B 0D ?? ?? ?? ?? 48 83 C1 78 E8 ?? ?? ?? ?? 48 8B 4E 30 48 8B 56 68 4C 8B 01 4D 8B 88 D8 00 00 00 4C 8B 00 41 FF D1 48 8B 5E 28 BA 0F 00 00 00 48 8B CB 44 0F B6 73 33 FF 15 ?? ?? ?? ?? 48 8B C8 FF 15 ?? ?? ?? ?? 84 C0 75 1B BA 12 00 00 00 48 8B CB FF 15 ?? ?? ?? ?? 48 8B C8 FF 15 ?? ?? ?? ?? 84 C0 74 02 B0 01 48 8B 4E 28 83 79 08 00 75 04 84 C0 74 6A 48 C7 44 24 50 FF FF FF FF 8B 81 6C 02 00 00 48 8D 14 40 48 8B 47 18 33 FF 48 8B 08 48 8D 1C D1 39 BE D8 02 00 00", 0, 0, 0,
     nullptr, nullptr,
     0, 322u, 0xd45cdde798dca271ull, 68u, 7u},
    // NG.ModelMaterialMT.submit
    {"NG.ModelMaterialMT.submit", 0, kCode, 0x131e0u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 48 89 6C 24 10 48 89 74 24 18 48 89 7C 24 20 41 56 48 83 EC 40 4C 8B 71 70 48 8B D9 48 8B 89 C0 01 00 00", 0, 0, 0,
     nullptr, nullptr,
     0, 309u, 0x248de0212850fd41ull, 75u, 3u},
    // NG.model_globals
    {"NG.model_globals", 0, kExport, 0x72e50u,
     nullptr, 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, "?globals@model@@3PEAVGlobalsMT@1@EA",
     0, 0u, 0x0000000000000000ull, 78u, 0u},
    // NG.iat.PropertiesSet_getTexture
    {"NG.iat.PropertiesSet_getTexture", 0, kImport, 0x57238u,
     nullptr, 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     "modeldesc.dll", "?getTexture@PropertiesSet@model@@QEBAAEBUTexture2dProperties@2@I@Z",
     0, 0u, 0x0000000000000000ull, 78u, 0u},
    // NG.iat.Texture2dProperties_valid
    {"NG.iat.Texture2dProperties_valid", 0, kImport, 0x57230u,
     nullptr, 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     "modeldesc.dll", "?valid@Texture2dProperties@model@@QEBA_NXZ",
     0, 0u, 0x0000000000000000ull, 78u, 0u},
    // DX.DX11Shader.vtbl
    {"DX.DX11Shader.vtbl", 2, kVtable, 0xb43b8u,
     ".?AVDX11Shader@RenderAPI@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 78u, 0u},
    // DX.DX11Shader.setTexture
    {"DX.DX11Shader.setTexture", 2, kCode, 0x1fd70u,
     nullptr, 0u, false, 0,
     kPattern, "4D 85 C0 0F 84 ?? ?? ?? ?? 55 56 48 83 EC 28 49 8B 00", 0, 0, 0,
     nullptr, nullptr,
     0, 246u, 0x49de9789dd38da6bull, 78u, 4u},
    // DX.DX11Shader.dtor
    {"DX.DX11Shader.dtor", 2, kCode, 0x1d3c0u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 57 48 83 EC 20 8B DA 48 8B F9 E8 ?? ?? ?? ?? F6 C3 01 74 0D BA 48 02 00 00", 0, 0, 0,
     nullptr, nullptr,
     0, 52u, 0x7d4cccf2095c9e02ull, 82u, 2u},
    // DX.DX11Texture.getDesc
    {"DX.DX11Texture.getDesc", 2, kCode, 0x479a0u,
     nullptr, 0u, false, 0,
     kPattern, "40 53 48 83 EC 20 8B 15 ?? ?? ?? ?? 48 8B D9 65 48 8B 04 25 58 00 00 00", 0, 0, 0,
     nullptr, nullptr,
     0, 125u, 0x1b34aa00b99e18d4ull, 84u, 10u},
    // DX.DX11Texture.compatible
    {"DX.DX11Texture.compatible", 2, kCode, 0x1df30u,
     nullptr, 0u, false, 0,
     kPattern, "83 C1 FB 83 F9 27 77 47 48 63 C1 4C 8D 05", 0, 0, 0,
     nullptr, nullptr,
     0, 118u, 0xde7fd4192d7e5969ull, 94u, 3u},
    // DX.DX11Texture.getSRV
    {"DX.DX11Texture.getSRV", 2, kCode, 0x47c60u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 57 48 83 EC 20 49 8B F8 48 8B D9", 0, 0, 0,
     nullptr, nullptr,
     0, 281u, 0x7a2dbefba2528574ull, 97u, 2u},
    // DX.DX11Texture.slot18
    {"DX.DX11Texture.slot18", 2, kCode, 0x120a0u,
     nullptr, 0u, false, 0,
     kPattern, "48 8B 49 10 90 48 8B 01 48 FF 60 40 CC CC CC CC", 0, 0, 0,
     nullptr, nullptr,
     0, 12u, 0xef463ebbaff4f85cull, 99u, 0u},
    // DX.DX11Texture.slot11
    {"DX.DX11Texture.slot11", 2, kCode, 0x11190u,
     nullptr, 0u, false, 0,
     kPattern, "48 8B 49 10 90 48 8B 01 48 FF 60 20 CC CC CC CC", 0, 0, 0,
     nullptr, nullptr,
     0, 12u, 0xef465ebbaff52ebcull, 99u, 0u},
    // DX.DX11TextureFromFileInternalImpl.vtbl
    {"DX.DX11TextureFromFileInternalImpl.vtbl", 2, kVtable, 0xb5b28u,
     ".?AVDX11TextureFromFileInternalImpl@RenderAPI@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 99u, 0u},
    // DX.DX11TextureArrayFromFileInternalImpl.vtbl
    {"DX.DX11TextureArrayFromFileInternalImpl.vtbl", 2, kVtable, 0xb5a60u,
     ".?AVDX11TextureArrayFromFileInternalImpl@RenderAPI@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 99u, 0u},
    // DX.DX11TextureInternalDummy.vtbl
    {"DX.DX11TextureInternalDummy.vtbl", 2, kVtable, 0xb6db0u,
     ".?AVDX11TextureInternalDummy@RenderAPI@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 99u, 0u},
    // DX.DX11TextureFromFileInternalImpl.slot4
    {"DX.DX11TextureFromFileInternalImpl.slot4", 2, kCode, 0x331f0u,
     nullptr, 0u, false, 0,
     kViaVtable, "8B 41 10 90 C3 CC CC CC CC CC CC CC CC CC CC CC", 0, 43, 4,
     nullptr, nullptr,
     0, 5u, 0xc3de40b3cb13c54eull, 99u, 0u},
    // DX.DX11TextureInternalDummy.slot4
    {"DX.DX11TextureInternalDummy.slot4", 2, kCode, 0x5250u,
     nullptr, 0u, false, 0,
     kViaVtable, "33 C0 C3 CC CC CC CC CC CC CC CC CC CC CC CC CC 0F B6 81 D8 00 00 00", 0, 45, 4,
     nullptr, nullptr,
     0, 3u, 0x58389c18233078ffull, 99u, 0u},
    // DX.ret0_stub
    {"DX.ret0_stub", 2, kCode, 0x5010u,
     nullptr, 0u, false, 0,
     kViaVtable, "C2 00 00 CC CC CC CC CC CC CC CC CC CC CC CC CC", 0, 44, 8,
     nullptr, nullptr,
     0, 3u, 0x69bc481c23de2d4dull, 99u, 0u},
    // DX.STechnique.vtbl
    {"DX.STechnique.vtbl", 2, kVtable, 0xb9608u,
     ".?AUSTechnique@D3DX11Effects@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 99u, 0u},
    // DX.SPassBlock.vtbl
    {"DX.SPassBlock.vtbl", 2, kVtable, 0xb96b0u,
     ".?AUSPassBlock@D3DX11Effects@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 99u, 0u},
    // DX.CEffect.vtbl
    {"DX.CEffect.vtbl", 2, kVtable, 0xbe700u,
     ".?AVCEffect@D3DX11Effects@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 99u, 0u},
    // DX.CEffect.GetDevice
    {"DX.CEffect.GetDevice", 2, kCode, 0x66a40u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 57 48 83 EC 20 48 8B DA 48 8B F9 48 85 D2 75 10", 0, 0, 0,
     nullptr, nullptr,
     0, 73u, 0x5b7086e6edd28963ull, 99u, 0u},
    // DX.SShaderGlobalVariable.vtbl
    {"DX.SShaderGlobalVariable.vtbl", 2, kVtable, 0xbd320u,
     ".?AUSShaderGlobalVariable@D3DX11Effects@@", 0u, false, 0,
     kPattern, nullptr, 0, 0, 0,
     nullptr, nullptr,
     0, 0u, 0x0000000000000000ull, 99u, 0u},
    // DX.SShaderGlobalVariable.GetVertexShader
    {"DX.SShaderGlobalVariable.GetVertexShader", 2, kCode, 0x5e790u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 57 48 83 EC 20 8B C2 49 8B F8 48 69 D8 88 00 00 00 48 03 59 08 48 8B CB E8 ?? ?? ?? ?? 83 F8 06", 0, 0, 0,
     nullptr, nullptr,
     0, 106u, 0xc701b9f46a175b1bull, 99u, 2u},
    // DX.DX11Shader.ctor.fieldStores
    {"DX.DX11Shader.ctor.fieldStores", 2, kCode, 0x1c883u,
     nullptr, 0u, false, 0,
     kPattern, "4C 89 6E 48 4C 89 6E 50 48 8D 4E 58 49 8B D4 E8", 0, 0, 0,
     nullptr, nullptr,
     -307, 831u, 0xac7033b60b9210f1ull, 101u, 18u},
    // DX.DX11Shader.keyBuilder
    {"DX.DX11Shader.keyBuilder", 2, kCode, 0xa1a60u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 4C 24 08 56 57 41 56 48 83 EC 40 48 C7 44 24 28 FE FF FF FF", 0, 0, 0,
     nullptr, nullptr,
     0, 393u, 0xbe8de22a183a4527ull, 119u, 16u},
    // DX.DX11Shader.macroBuilder
    {"DX.DX11Shader.macroBuilder", 2, kCode, 0xa19d0u,
     nullptr, 0u, false, 0,
     kPattern, "48 89 5C 24 08 48 89 74 24 18 57 48 83 EC 20 49 8B D8", 0, 0, 0,
     nullptr, nullptr,
     0, 133u, 0x761705a98500ca35ull, 135u, 1u},
};

inline constexpr Hash kHashes[] = {
    {NG_ModelMaterialMT_drawShadow, 0, 322u, 0x49534eb2132118cfull, 0xd45cdde798dca271ull},
    {NG_ModelMaterialMT_submit, 0, 309u, 0xfa5b29e55d76ca0cull, 0x248de0212850fd41ull},
    {DX_DX11Shader_setTexture, 0, 246u, 0xd7c1df3dc2fb5bccull, 0x49de9789dd38da6bull},
    {DX_DX11Texture_getDesc, 0, 125u, 0x88604560f884ef35ull, 0x1b34aa00b99e18d4ull},
    {DX_DX11Texture_compatible, 0, 82u, 0x275cd10c465c1af9ull, 0x6f4e777e1bfe59ccull},
    {DX_DX11Texture_getSRV, 0, 281u, 0xf31eee13d0c2176dull, 0x7a2dbefba2528574ull},
    {DX_CEffect_GetDevice, 0, 73u, 0x5b7086e6edd28963ull, 0x5b7086e6edd28963ull},
    {DX_SShaderGlobalVariable_GetVertexShader, 0, 106u, 0xc13a45cdca71d942ull, 0xc701b9f46a175b1bull},
    {DX_DX11Shader_ctor_fieldStores, 0, 85u, 0xd87db5cfa62bb7b3ull, 0xc0489dfa6ca3f304ull},
    {DX_DX11Shader_keyBuilder, 0, 392u, 0xdfc520925718cb4full, 0x9614f7d8aab8ec71ull},
    {DX_DX11Shader_macroBuilder, 0, 133u, 0xefaa4847922b6b10ull, 0x761705a98500ca35ull},
};

}  // namespace hooksig
