// Runtime relocation of the production hooks' DCS locations.
//
// Every hook keeps its recorded RVA and its install-time checks (RTTI, slot
// targets, prologue bytes, FNV code hashes). It asks this resolver for the
// address instead of using the constant directly:
//   - on the DCS build the RVAs were derived from (module timestamp and size
//     equal to hook_sigs.h's kModules), or with [General] SigScan=0, every
//     call returns the recorded value and every check is today's exact check;
//   - on another build, each location of the module is looked up once, the
//     first time a hook asks for one: the recorded RVA if its signature still
//     matches there, else the unique match (RTTI type name + COL offset for
//     vtables, wildcard pattern for code, import/export name), else 0. A code
//     location is only accepted when its whole function hashes the same with
//     every displacement masked (masked FNV, hook_sigs.h), so code whose
//     logic changed resolves to 0 and its hook stays off. The hooks' own
//     checks then run against the resolved address; CodeIs, BytesAre and
//     SlotIs give the masked/relocated variants of those checks.
// Moves are logged ("reloc: <id> moved 0x.. -> 0x.."), with one summary
// line per module. Results are cached per id for the process.
//
// Signatures come from src/hook_sigs.h, generated by tools/gen_hook_sigs.py;
// docs/research/PATCH_PROCEDURE.md describes the workflow. Header-only,
// C++17; reads only inside the mapped image's sections.
#pragma once

#include <windows.h>

#include <atomic>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <mutex>
#include <vector>

#include "hook_sigs.h"
#include "sigscan.h"

namespace reloc {

using hooksig::Id;
using hooksig::Loc;

inline std::atomic<bool> g_enabled{true};  // [General] SigScan
inline bool g_forceScan = false;           // tests: resolve on the analysed build too
// Set by the payload: its Log, and SlotOriginal (a hooked slot reports DCS's
// own pointer). Null: no log, plain reads.
inline void (*g_log)(const char* line) = nullptr;
inline void* (*g_slotRead)(void** slot) = nullptr;
// Tests: maps module names to image-resource mappings. Null: GetModuleHandleW.
inline const uint8_t* (*g_moduleBase)(const wchar_t* name) = nullptr;

inline void Logf(const char* fmt, ...) {
  if (!g_log) return;
  char line[1024];
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(line, sizeof(line), fmt, ap);
  va_end(ap);
  g_log(line);
}

// ---------------------------------------------------------------------------
// Resolution of one table (the generated one, or a test's)
// ---------------------------------------------------------------------------

struct Table {
  const Loc* locs;
  size_t count;
  const hooksig::Mask* masks;
  const hooksig::Hash* hashes;
  size_t hashCount;
};

inline Table Generated() {
  return {hooksig::kLocs, hooksig::kCount, hooksig::kMasks, hooksig::kHashes,
          sizeof(hooksig::kHashes) / sizeof(hooksig::kHashes[0])};
}

inline uint32_t SizeOf(const uint8_t* base) { return sigscan::SizeOfImage(base); }

inline bool InCode(const uint8_t* base, const uint8_t* p, size_t n) {
  bool in = false;
  sigscan::ForEachCodeSection(base, [&](sigscan::Range r) { in |= p >= r.begin && p + n <= r.end; });
  return in;
}

// A pointer stored in the image (vtable entry, COL pointer) as an RVA: the
// image may be relocated (loaded module) or not (image-resource mapping).
inline uint32_t PtrToRva(const uint8_t* base, const void* p) {
  const uint64_t v = reinterpret_cast<uint64_t>(p), b = reinterpret_cast<uint64_t>(base);
  const uint32_t size = SizeOf(base);
  if (v >= b && v < b + size) return static_cast<uint32_t>(v - b);
  const IMAGE_NT_HEADERS64* nt = sigscan::NtHeaders(base);
  const uint64_t pref = nt ? nt->OptionalHeader.ImageBase : 0;
  if (v >= pref && v < pref + size) return static_cast<uint32_t>(v - pref);
  return 0;
}

inline void* ReadSlot(void** slot) { return g_slotRead ? g_slotRead(slot) : *slot; }

inline uint64_t Fnv(const uint8_t* p, size_t n) {
  uint64_t h = 0xcbf29ce484222325ull;
  for (size_t i = 0; i < n; ++i) {
    h ^= p[i];
    h *= 0x100000001b3ull;
  }
  return h;
}

// FNV of [rva + at, + len) with loc's masked bytes zeroed (loc's masks are
// relative to rva, its resolved address). False when out of the image.
inline bool MaskedFnv(const uint8_t* base, const Table& t, const Loc& l, uint32_t rva, int32_t at, uint32_t len,
                      uint64_t* out) {
  const uint8_t* p = base + rva + at;
  if (!sigscan::InImage(base, p, len)) return false;
  std::vector<uint8_t> buf(p, p + len);
  for (uint32_t i = 0; i < l.maskCount; ++i) {
    const hooksig::Mask& m = t.masks[l.maskFirst + i];
    for (int32_t k = m.at; k < m.at + m.len; ++k)
      if (k >= at && k < at + static_cast<int32_t>(len)) buf[k - at] = 0;
  }
  *out = Fnv(buf.data(), buf.size());
  return true;
}

// The vtable at rva has the RTTI name (exactly, or as a prefix) and COL offset.
inline bool VtableIs(const uint8_t* base, uint32_t rva, const Loc& l) {
  auto vt = reinterpret_cast<void* const*>(base + rva);
  if (!rva || !sigscan::InImage(base, vt - 1, 8)) return false;
  const uint32_t colRva = PtrToRva(base, vt[-1]);
  auto* col = reinterpret_cast<const sigscan::Col*>(base + colRva);
  if (!colRva || !sigscan::InImage(base, col, sizeof(*col)) || col->signature != 1 || col->offset != l.colOffset)
    return false;
  const char* name = sigscan::CStrAt(base, col->typeDescriptor + 16);
  const size_t n = strlen(l.rtti);
  return name && strncmp(name, l.rtti, n) == 0 && (l.rttiPrefix || name[n] == 0);
}

// Entries pointing into code before the first one that does not.
inline uint32_t VtableLen(const uint8_t* base, uint32_t rva) {
  uint32_t n = 0;
  for (auto** vt = reinterpret_cast<void**>(const_cast<uint8_t*>(base) + rva);
       n < 4096 && sigscan::InImage(base, vt + n, 8); ++n) {
    const uint32_t f = PtrToRva(base, ReadSlot(vt + n));
    if (!f || !InCode(base, base + f, 1)) break;
  }
  return n;
}

// `jmp [rip+disp]` thunks whose slot is the IAT slot `slotRva`: the unique one, or 0.
inline uint32_t ImportThunk(const uint8_t* base, uint32_t slotRva, int* count) {
  uint32_t found = 0;
  *count = 0;
  sigscan::ForEachCodeSection(base, [&](sigscan::Range r) {
    for (const uint8_t* p = r.begin; p + 6 <= r.end; ++p) {
      p = static_cast<const uint8_t*>(memchr(p, 0xFF, static_cast<size_t>(r.end - p) - 5));
      if (!p) break;
      if (p[1] != 0x25) continue;
      int32_t d;
      memcpy(&d, p + 2, 4);
      if (p + 6 + d == base + slotRva) {
        found = static_cast<uint32_t>(p - base);
        ++*count;
      }
    }
  });
  return *count == 1 ? found : 0;
}

// Resolves t.locs[i] in the image at base (recursive for kViaVtable). memo
// holds UINT32_MAX for "not resolved yet". why receives the reason for 0.
inline uint32_t ResolveIn(const uint8_t* base, const Table& t, size_t i, std::vector<uint32_t>& memo,
                          const char** why) {
  if (memo[i] != UINT32_MAX) return memo[i];
  const Loc& l = t.locs[i];
  uint32_t rva = 0;
  *why = nullptr;
  int n = 0;
  switch (l.kind) {
    case hooksig::kVtable:
      if (VtableIs(base, l.rva, l)) {
        rva = l.rva;
      } else {
        void** vt = sigscan::FindVtable(base, l.rtti, l.colOffset, l.rttiPrefix, &n);
        rva = vt ? static_cast<uint32_t>(reinterpret_cast<uint8_t*>(vt) - base) : 0;
        if (!rva) *why = n ? "RTTI name not unique" : "RTTI name not found";
      }
      if (rva && l.vtableLen && VtableLen(base, rva) != l.vtableLen) {
        rva = 0;
        *why = "vtable length differs";
      }
      break;
    case hooksig::kImport:
      rva = sigscan::ImportSlotRva(base, l.dll, l.name);
      if (!rva) *why = "import not found";
      break;
    case hooksig::kExport:
      rva = sigscan::ExportRva(base, l.name);
      if (!rva) *why = "export not found";
      break;
    case hooksig::kCode: {
      sigscan::Pattern pat;
      const bool hasPat = l.pattern && sigscan::Parse(l.pattern, pat);
      auto matchesAt = [&](uint32_t at) {
        const uint8_t* p = base + at - l.patOffset;
        return at && InCode(base, p, pat.size()) && sigscan::MatchAt(p, pat);
      };
      if (l.via == hooksig::kPattern) {
        if (hasPat && matchesAt(l.rva)) {
          rva = l.rva;
        } else {
          uint8_t* hit = hasPat ? sigscan::FindUnique(base, l.pattern, l.patOffset, &n) : nullptr;
          rva = hit ? static_cast<uint32_t>(hit - base) : 0;
          if (!rva) *why = n > 1 ? "pattern not unique" : "pattern not found";
        }
      } else if (l.via == hooksig::kViaVtable) {
        const char* vwhy = nullptr;
        const uint32_t vt = ResolveIn(base, t, l.vtable, memo, &vwhy);
        void** slot = reinterpret_cast<void**>(const_cast<uint8_t*>(base) + vt) + l.slot;
        rva = vt && sigscan::InImage(base, slot, 8) ? PtrToRva(base, ReadSlot(slot)) : 0;
        if (!vt) *why = "its vtable was not found";
        else if (rva && hasPat && !matchesAt(rva)) rva = 0, *why = "slot target does not match the pattern";
        else if (!rva) *why = "slot target outside the module";
      } else {
        const uint32_t slot = sigscan::ImportSlotRva(base, l.dll, l.name);
        rva = slot ? ImportThunk(base, slot, &n) : 0;
        if (!rva) *why = slot ? (n ? "import thunk not unique" : "import thunk not found") : "import not found";
      }
      uint64_t h = 0;
      if (rva && l.fnLen && (!MaskedFnv(base, t, l, rva, l.fnAt, l.fnLen, &h) || h != l.fnHash)) {
        rva = 0;
        *why = "code differs (masked hash of its function)";
      }
      break;
    }
  }
  memo[i] = rva;
  return rva;
}

// A CodeIs check of loc i at its resolved address rva: the exact hash, else
// the masked one. False when the table has no such check.
inline bool HashIn(const uint8_t* base, const Table& t, size_t i, uint32_t rva, uint32_t begin, uint32_t end,
                   uint64_t hash, bool* masked = nullptr) {
  const Loc& l = t.locs[i];
  if (masked) *masked = false;
  for (size_t k = 0; k < t.hashCount; ++k) {
    const hooksig::Hash& c = t.hashes[k];
    if (c.loc != i || l.rva + c.at != begin || c.len != end - begin || c.hash != hash) continue;
    const uint8_t* p = base + rva + c.at;
    if (!rva || !sigscan::InImage(base, p, c.len)) return false;
    if (Fnv(p, c.len) == hash) return true;
    uint64_t h = 0;
    if (masked) *masked = true;
    return MaskedFnv(base, t, l, rva, c.at, c.len, &h) && h == c.masked;
  }
  return false;
}

// ---------------------------------------------------------------------------
// The payload's resolver (generated table, loaded modules)
// ---------------------------------------------------------------------------

constexpr size_t kModuleCount = sizeof(hooksig::kModules) / sizeof(hooksig::kModules[0]);

struct State {
  std::mutex mutex;
  const uint8_t* base[kModuleCount] = {};
  bool scanned[kModuleCount] = {};  // false: the analysed build (or SigScan=0), recorded RVAs
  uint32_t rva[hooksig::kCount] = {};
  bool warned[hooksig::kCount] = {};
};
inline State g_state;

inline const uint8_t* ModuleBase(uint8_t module) {
  const wchar_t* name = hooksig::kModules[module].name;
  return g_moduleBase ? g_moduleBase(name) : reinterpret_cast<const uint8_t*>(GetModuleHandleW(name));
}

inline bool IsAnalysedBuild(const uint8_t* base, uint8_t module) {
  const IMAGE_NT_HEADERS64* nt = sigscan::NtHeaders(base);
  return nt && nt->FileHeader.TimeDateStamp == hooksig::kModules[module].timestamp &&
         nt->OptionalHeader.SizeOfImage == hooksig::kModules[module].sizeOfImage;
}

// Resolves every location of the module once (caller holds the mutex).
inline void PrepareModule(uint8_t module, const uint8_t* base) {
  State& s = g_state;
  if (s.base[module] == base) return;
  s.base[module] = base;
  const Table t = Generated();
  const IMAGE_NT_HEADERS64* nt = sigscan::NtHeaders(base);
  const uint32_t stamp = nt ? nt->FileHeader.TimeDateStamp : 0;
  int total = 0, moved = 0, lost = 0;
  if (IsAnalysedBuild(base, module) && !g_forceScan) {
    s.scanned[module] = false;
    for (size_t i = 0; i < t.count; ++i)
      if (t.locs[i].module == module) s.rva[i] = t.locs[i].rva, ++total;
    Logf("reloc: %ls is the analysed build (0x%08x): %d recorded locations used as is",
         hooksig::kModules[module].name, stamp, total);
    return;
  }
  s.scanned[module] = true;
  std::vector<uint32_t> memo(t.count, UINT32_MAX);
  for (size_t i = 0; i < t.count; ++i) {
    if (t.locs[i].module != module) continue;
    ++total;
    const char* why = nullptr;
    const uint32_t r = ResolveIn(base, t, i, memo, &why);
    s.rva[i] = r;
    if (!r) {
      ++lost;
      Logf("reloc: %s not found (%s); hooks that need it stay off", t.locs[i].id, why ? why : "?");
    } else if (r != t.locs[i].rva) {
      ++moved;
      Logf("reloc: %s moved 0x%x -> 0x%x", t.locs[i].id, t.locs[i].rva, r);
    }
  }
  Logf("reloc: %ls is not the analysed build (0x%08x, analysed 0x%08x): %d locations, %d unchanged, %d relocated, "
       "%d not found",
       hooksig::kModules[module].name, stamp, hooksig::kModules[module].timestamp, total, total - moved - lost, moved,
       lost);
}

// The RVA to use for `id`: `recorded` (the source constant) on the analysed
// build, with SigScan=0, or while the module is not loaded; else the resolved
// RVA, 0 when it was not found.
inline uint32_t Rva(Id id, uint32_t recorded) {
  const Loc& l = hooksig::kLocs[id];
  if (!g_enabled.load(std::memory_order_relaxed)) return recorded;
  const uint8_t* base = ModuleBase(l.module);
  if (!base) return recorded;
  std::lock_guard<std::mutex> lock(g_state.mutex);
  if (recorded != l.rva) {
    if (!g_state.warned[id]) Logf("reloc: %s: the source has 0x%x, hook_sigs.h 0x%x (regenerate it); recorded "
                                  "address used", l.id, recorded, l.rva);
    g_state.warned[id] = true;
    return recorded;
  }
  PrepareModule(l.module, base);
  return g_state.rva[id];
}
inline uint32_t Rva(Id id) { return Rva(id, hooksig::kLocs[id].rva); }

// True when id's module is not the analysed build and was scanned.
inline bool Scanned(Id id) {
  if (!g_enabled.load(std::memory_order_relaxed)) return false;
  Rva(id);
  std::lock_guard<std::mutex> lock(g_state.mutex);
  return g_state.scanned[hooksig::kLocs[id].module];
}

inline bool ReadCode(const uint8_t* p, uint8_t* out, size_t n) {
  __try {
    memcpy(out, p, n);
    return true;
  } __except (EXCEPTION_EXECUTE_HANDLER) {
    return false;
  }
}

// shadowtex::CodeIs with a location: [begin, end) recorded RVAs of the
// check. The analysed build: the exact hash at the recorded range (today's
// check). Otherwise at the resolved address: the exact hash, else the
// masked hash from hook_sigs.h.
inline bool CodeIs(Id id, uint8_t* base, uint32_t begin, uint32_t end, uint64_t hash) {
  const uint32_t rva = Rva(id);
  if (!Scanned(id)) {
    uint8_t buf[512];
    const size_t n = end - begin;
    return n <= sizeof(buf) && ReadCode(base + begin, buf, n) && Fnv(buf, n) == hash;
  }
  bool masked = false;
  const bool ok = HashIn(base, Generated(), id, rva, begin, end, hash, &masked);
  if (ok && masked) Logf("reloc: %s: code at +0x%x matches with displacements masked", hooksig::kLocs[id].id,
                         begin - hooksig::kLocs[id].rva);
  return ok;
}

// memcmp of bytes read at id's location against the expected ones; when
// scanned, the bytes hook_sigs.h masks (displacements) are not compared.
inline bool BytesAre(Id id, const uint8_t* cur, const uint8_t* expected, size_t n) {
  if (!Scanned(id)) return memcmp(cur, expected, n) == 0;
  const Loc& l = hooksig::kLocs[id];
  for (size_t k = 0; k < n; ++k) {
    bool masked = false;
    for (uint32_t i = 0; i < l.maskCount && !masked; ++i) {
      const hooksig::Mask& m = hooksig::kMasks[l.maskFirst + i];
      masked = static_cast<int32_t>(k) >= m.at && static_cast<int32_t>(k) < m.at + m.len;
    }
    if (!masked && cur[k] != expected[k]) return false;
  }
  return true;
}

// A slot target the hook does not compare today: always true on the analysed
// build; when scanned it must be id's resolved function (a vtable found by
// RTTI alone could have its methods in other slots).
inline bool SlotIs(Id id, const uint8_t* base, const void* target) {
  if (!Scanned(id)) return true;
  const uint32_t r = Rva(id);
  return r && target == base + r;
}

}  // namespace reloc
