// Runtime signature scanning for DCS modules (used by reloc.h).
//
// Lets a hook find its target in a DCS build other than the one it was
// written against, instead of trusting a fixed RVA:
//   - FindPattern / FindUnique: an IDA-style pattern ("48 8B 05 ?? ?? ?? ??")
//     in a module's code sections, with a uniqueness check;
//   - FindVtable: a vtable by its RTTI type name (and the COL's offset field,
//     which tells a class's primary vtable from its secondary ones), the same
//     lookup allocslab::RttiIs verifies, done in reverse;
//   - RttiName, RipTarget, Rel32Target: small helpers for verifying a match.
// Patterns and RTTI names come from tools/hooks_manifest.json (generated by
// tools/extract_manifest.py); docs/research/PATCH_PROCEDURE.md describes how
// to move a hook from a fixed RVA to these lookups.
//
// Everything works on a module image mapped by the loader (an HMODULE, or a
// LOAD_LIBRARY_AS_IMAGE_RESOURCE mapping) and only reads inside the image's
// section ranges, so it needs no SEH. Header-only, C++17, no allocation
// except in Pattern.
#pragma once

#include <windows.h>

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <vector>

namespace sigscan {

// ---------------------------------------------------------------------------
// Patterns
// ---------------------------------------------------------------------------

struct Pattern {
  std::vector<uint8_t> bytes;
  std::vector<uint8_t> care;  // 1 = byte must match, 0 = wildcard
  size_t size() const { return bytes.size(); }
};

inline int HexDigit(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

// Parses "48 8B ?? 05 ?" (space separated; "?" or "??" is a wildcard).
// Returns false on malformed input, an empty pattern, or one that is all
// wildcards.
inline bool Parse(const char* text, Pattern& out) {
  out.bytes.clear();
  out.care.clear();
  bool anyFixed = false;
  const char* p = text;
  while (*p) {
    while (*p == ' ' || *p == '\t') ++p;
    if (!*p) break;
    if (p[0] == '?') {
      p += (p[1] == '?') ? 2 : 1;
      out.bytes.push_back(0);
      out.care.push_back(0);
    } else {
      const int hi = HexDigit(p[0]), lo = HexDigit(p[1]);
      if (hi < 0 || lo < 0) return false;
      out.bytes.push_back(static_cast<uint8_t>(hi * 16 + lo));
      out.care.push_back(1);
      anyFixed = true;
      p += 2;
    }
    if (*p && *p != ' ' && *p != '\t') return false;
  }
  return anyFixed;
}

struct Range {
  const uint8_t* begin = nullptr;
  const uint8_t* end = nullptr;
};

inline bool MatchAt(const uint8_t* at, const Pattern& pat) {
  for (size_t i = 0; i < pat.size(); ++i)
    if (pat.care[i] && at[i] != pat.bytes[i]) return false;
  return true;
}

// Finds matches of `pat` in [r.begin, r.end). Stores up to `max` match
// addresses in out (may be null) and returns the total number of matches,
// counting at most `countLimit` (2 is enough for a uniqueness check).
inline size_t FindAll(Range r, const Pattern& pat, const uint8_t** out, size_t max, size_t countLimit = SIZE_MAX) {
  if (!pat.size() || !r.begin || r.end < r.begin || static_cast<size_t>(r.end - r.begin) < pat.size()) return 0;
  // Anchor on the first fixed byte: memchr does the scanning.
  size_t first = 0;
  while (!pat.care[first]) ++first;
  const uint8_t key = pat.bytes[first];
  const uint8_t* last = r.end - pat.size();
  size_t n = 0;
  for (const uint8_t* p = r.begin + first; p <= last + first;) {
    p = static_cast<const uint8_t*>(memchr(p, key, static_cast<size_t>(last + first - p) + 1));
    if (!p) break;
    const uint8_t* cand = p - first;
    if (MatchAt(cand, pat)) {
      if (out && n < max) out[n] = cand;
      if (++n >= countLimit) break;
    }
    ++p;
  }
  return n;
}

// ---------------------------------------------------------------------------
// Module layout
// ---------------------------------------------------------------------------

// Strips the tag bits LoadLibraryEx sets on data/image-resource mappings.
inline const uint8_t* ImageBase(HMODULE m) {
  return reinterpret_cast<const uint8_t*>(reinterpret_cast<uintptr_t>(m) & ~static_cast<uintptr_t>(3));
}

inline const IMAGE_NT_HEADERS64* NtHeaders(const uint8_t* base) {
  if (!base) return nullptr;
  auto* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(base);
  if (dos->e_magic != IMAGE_DOS_SIGNATURE) return nullptr;
  auto* nt = reinterpret_cast<const IMAGE_NT_HEADERS64*>(base + dos->e_lfanew);
  if (nt->Signature != IMAGE_NT_SIGNATURE || nt->OptionalHeader.Magic != IMAGE_NT_OPTIONAL_HDR64_MAGIC) return nullptr;
  return nt;
}

// Section by name (".text", ".rdata", ".data"). Returns false when absent.
inline bool Section(const uint8_t* base, const char* name, Range& out) {
  const IMAGE_NT_HEADERS64* nt = NtHeaders(base);
  if (!nt) return false;
  const IMAGE_SECTION_HEADER* s = IMAGE_FIRST_SECTION(nt);
  for (WORD i = 0; i < nt->FileHeader.NumberOfSections; ++i, ++s) {
    char n[9] = {};
    memcpy(n, s->Name, 8);
    if (strcmp(n, name) == 0) {
      out.begin = base + s->VirtualAddress;
      out.end = out.begin + (s->Misc.VirtualSize ? s->Misc.VirtualSize : s->SizeOfRawData);
      return true;
    }
  }
  return false;
}

inline uint32_t SizeOfImage(const uint8_t* base) {
  const IMAGE_NT_HEADERS64* nt = NtHeaders(base);
  return nt ? nt->OptionalHeader.SizeOfImage : 0;
}

// Calls f(Range) for every executable section.
template <typename F>
void ForEachCodeSection(const uint8_t* base, F&& f) {
  const IMAGE_NT_HEADERS64* nt = NtHeaders(base);
  if (!nt) return;
  const IMAGE_SECTION_HEADER* s = IMAGE_FIRST_SECTION(nt);
  for (WORD i = 0; i < nt->FileHeader.NumberOfSections; ++i, ++s)
    if (s->Characteristics & IMAGE_SCN_MEM_EXECUTE)
      f(Range{base + s->VirtualAddress, base + s->VirtualAddress + (s->Misc.VirtualSize ? s->Misc.VirtualSize : s->SizeOfRawData)});
}

// Number of matches of `pattern` in the module's code (counting stops at 2),
// and the match + offset when there is exactly one; nullptr otherwise
// (malformed pattern, no match, or ambiguous). `offset` is the manifest's
// signature offset: the location minus the pattern start.
inline uint8_t* FindUnique(const uint8_t* base, const char* pattern, ptrdiff_t offset = 0, int* count = nullptr) {
  Pattern pat;
  if (count) *count = 0;
  if (!Parse(pattern, pat)) return nullptr;
  const uint8_t* hit = nullptr;
  size_t n = 0;
  ForEachCodeSection(base, [&](Range r) {
    if (n >= 2) return;
    const uint8_t* h[2];
    const size_t k = FindAll(r, pat, h, 2, 2 - n);
    if (k && !n) hit = h[0];
    n += k;
  });
  if (count) *count = static_cast<int>(n);
  return n == 1 ? const_cast<uint8_t*>(hit) + offset : nullptr;
}

inline uint8_t* FindUnique(HMODULE m, const char* pattern, ptrdiff_t offset = 0, int* count = nullptr) {
  return FindUnique(ImageBase(m), pattern, offset, count);
}

// ---------------------------------------------------------------------------
// Instruction helpers
// ---------------------------------------------------------------------------

// Target of a RIP-relative operand: disp32 at insn + dispOffset, instruction
// length insnLen (e.g. 48 8B 05 disp32: dispOffset 3, insnLen 7).
inline uint8_t* RipTarget(const uint8_t* insn, int dispOffset, int insnLen) {
  int32_t d;
  memcpy(&d, insn + dispOffset, 4);
  return const_cast<uint8_t*>(insn) + insnLen + d;
}

// Target of an E8/E9 rel32 call or jump; nullptr for anything else.
inline uint8_t* Rel32Target(const uint8_t* insn) {
  if (insn[0] != 0xE8 && insn[0] != 0xE9) return nullptr;
  return RipTarget(insn, 1, 5);
}

// ---------------------------------------------------------------------------
// RTTI (MSVC x64: vtable[-1] -> complete object locator, all fields RVAs)
// ---------------------------------------------------------------------------

struct Col {  // RTTICompleteObjectLocator, signature 1 (image-relative)
  uint32_t signature, offset, cdOffset, typeDescriptor, classDescriptor, self;
};

inline bool InImage(const uint8_t* base, const void* p, size_t n) {
  const uint32_t size = SizeOfImage(base);
  auto* q = static_cast<const uint8_t*>(p);
  return q >= base && q + n <= base + size;
}

// The RTTI type name of a vtable (".?AVFoo@ns@@"), or nullptr. Same lookup as
// allocslab::RttiIs, bounds-checked against the image instead of SEH.
inline const char* RttiName(const uint8_t* base, void* const* vtbl) {
  if (!InImage(base, vtbl - 1, 8)) return nullptr;
  auto* col = static_cast<const Col*>(vtbl[-1]);
  if (!InImage(base, col, sizeof(Col)) || col->signature != 1) return nullptr;
  const uint8_t* name = base + col->typeDescriptor + 16;
  if (!InImage(base, name, 1)) return nullptr;
  return reinterpret_cast<const char*>(name);
}

// The vtable whose complete object locator names `rttiName` (exactly, or as
// a prefix when `prefix`) with COL offset `colOffset` (0 = the class's primary
// vtable; a secondary base's vtable has that base's offset). Returns it when
// there is exactly one, else nullptr; *count receives the number found.
// Pointer values in .rdata are compared with base + RVA and, for images that
// were mapped without relocation, with the header's ImageBase + RVA.
inline void** FindVtable(const uint8_t* base, const char* rttiName, uint32_t colOffset = 0, bool prefix = false,
                         int* count = nullptr) {
  if (count) *count = 0;
  Range rdata, data;
  if (!Section(base, ".rdata", rdata)) return nullptr;
  const IMAGE_NT_HEADERS64* nt = NtHeaders(base);
  const uint64_t bases[2] = {reinterpret_cast<uint64_t>(base), nt->OptionalHeader.ImageBase};
  const size_t nameLen = strlen(rttiName) + (prefix ? 0 : 1);  // with the terminator unless prefix
  void** found = nullptr;
  int n = 0;
  // Type descriptors live in .data: {pVFTable, spare, name[]}.
  auto scanTd = [&](Range r) {
    for (const uint8_t* p = r.begin; p + nameLen <= r.end; ++p) {
      p = static_cast<const uint8_t*>(memchr(p, rttiName[0], static_cast<size_t>(r.end - p)));
      if (!p || p + nameLen > r.end) break;
      if (memcmp(p, rttiName, nameLen) != 0 || p - 16 < base) continue;
      const uint32_t td = static_cast<uint32_t>(p - 16 - base);
      // Complete object locators in .rdata naming this descriptor.
      for (const uint8_t* c = rdata.begin; c + sizeof(Col) <= rdata.end; c += 4) {
        const Col* col = reinterpret_cast<const Col*>(c);
        if (col->typeDescriptor != td || col->signature != 1 || col->self != static_cast<uint32_t>(c - base) ||
            col->offset != colOffset)
          continue;
        // The vtable follows the pointer to its COL.
        for (uint64_t b : bases) {
          const uint64_t want = b + col->self;
          bool any = false;
          for (const uint8_t* q = rdata.begin; q + 16 <= rdata.end; q += 8) {
            uint64_t v;
            memcpy(&v, q, 8);
            if (v == want) {
              found = reinterpret_cast<void**>(const_cast<uint8_t*>(q + 8));
              ++n;
              any = true;
            }
          }
          if (any || bases[0] == bases[1]) break;
        }
      }
    }
  };
  if (Section(base, ".data", data)) scanTd(data);
  scanTd(rdata);  // some linkers merge .data-like RTTI into .rdata
  if (count) *count = n;
  return n == 1 ? found : nullptr;
}

inline void** FindVtable(HMODULE m, const char* rttiName, uint32_t colOffset = 0, bool prefix = false,
                         int* count = nullptr) {
  return FindVtable(ImageBase(m), rttiName, colOffset, prefix, count);
}

// ---------------------------------------------------------------------------
// Imports and exports by name (work on image-resource mappings too)
// ---------------------------------------------------------------------------

inline const char* CStrAt(const uint8_t* base, uint32_t rva) {
  const char* s = reinterpret_cast<const char*>(base + rva);
  return rva && InImage(base, s, 1) ? s : nullptr;
}

// RVA of the IAT slot importing `dll!name` (dll compared case-insensitively), or 0.
inline uint32_t ImportSlotRva(const uint8_t* base, const char* dll, const char* name) {
  const IMAGE_NT_HEADERS64* nt = NtHeaders(base);
  if (!nt) return 0;
  const IMAGE_DATA_DIRECTORY& dir = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];
  if (!dir.VirtualAddress) return 0;
  for (auto* imp = reinterpret_cast<const IMAGE_IMPORT_DESCRIPTOR*>(base + dir.VirtualAddress);
       InImage(base, imp, sizeof(*imp)) && imp->Name; ++imp) {
    const char* d = CStrAt(base, imp->Name);
    if (!d || _stricmp(d, dll) != 0) continue;
    const uint32_t names = imp->OriginalFirstThunk ? imp->OriginalFirstThunk : imp->FirstThunk;
    for (uint32_t i = 0;; ++i) {
      auto* t = reinterpret_cast<const IMAGE_THUNK_DATA64*>(base + names + 8 * i);
      if (!InImage(base, t, 8) || !t->u1.AddressOfData) break;
      if (IMAGE_SNAP_BY_ORDINAL64(t->u1.Ordinal) || t->u1.AddressOfData >> 32) continue;
      const char* n = CStrAt(base, static_cast<uint32_t>(t->u1.AddressOfData) + 2);
      if (n && strcmp(n, name) == 0) return imp->FirstThunk + 8 * i;
    }
  }
  return 0;
}

// RVA of the export `name` (code or data), or 0 (also for forwarders).
inline uint32_t ExportRva(const uint8_t* base, const char* name) {
  const IMAGE_NT_HEADERS64* nt = NtHeaders(base);
  if (!nt) return 0;
  const IMAGE_DATA_DIRECTORY& dir = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT];
  auto* ed = reinterpret_cast<const IMAGE_EXPORT_DIRECTORY*>(base + dir.VirtualAddress);
  if (!dir.VirtualAddress || !InImage(base, ed, sizeof(*ed))) return 0;
  auto* names = reinterpret_cast<const uint32_t*>(base + ed->AddressOfNames);
  auto* ords = reinterpret_cast<const uint16_t*>(base + ed->AddressOfNameOrdinals);
  auto* funcs = reinterpret_cast<const uint32_t*>(base + ed->AddressOfFunctions);
  if (!InImage(base, names, 4 * ed->NumberOfNames) || !InImage(base, ords, 2 * ed->NumberOfNames) ||
      !InImage(base, funcs, 4 * ed->NumberOfFunctions))
    return 0;
  for (DWORD i = 0; i < ed->NumberOfNames; ++i) {
    const char* n = CStrAt(base, names[i]);
    if (!n || strcmp(n, name) != 0 || ords[i] >= ed->NumberOfFunctions) continue;
    const uint32_t rva = funcs[ords[i]];
    return rva >= dir.VirtualAddress && rva < dir.VirtualAddress + dir.Size ? 0 : rva;
  }
  return 0;
}

}  // namespace sigscan
